#
IS:
  Plain:
    Block: GRASS_BLOCK
    Name: Test
    Lore: WHYYY
    Schematic: IslandPlain.schem
    Slot: 0

CustomGenerator:
  Enable: true   #true or false
  name:
    1: <color:gray>The beginning
    2: <color:#383D45>Time for an upgrade
    3: <color:#D5D5D5>The iron age
    4: <color:yellow>The gold age
    5: <gradient:#FC0000:#5f1313>Automation time !
    6: <color:#9FF8E5>DIAMOND!
    7: <color:#40F082>The final generator <color:#002C00>(GG!)
  level:
    1:
      - Stone:54.5
      - granite:10
      - diorite:10
      - andesite:10
      - gravel:10
      - coal_ore:4
      - iron_ore:1
      - emerald_ore:0.5
    2:
      - Stone:50
      - granite:7
      - diorite:7
      - andesite:7
      - gravel:7
      - coal_ore:10.5
      - DEEPSLATE_COAL_ORE:6.5
      - iron_ore:4
      - DEEPSLATE:1
    3:
      - Stone:40
      - granite:5
      - diorite:5
      - andesite:5
      - gravel:5
      - coal_ore:10.5
      - DEEPSLATE_COAL_ORE:7.5
      - iron_ore:10
      - deepslate_iron_ore:8
      - DEEPSLATE:3
      - gold_ore:1
    4:
      - Stone:35
      - granite:2.5
      - diorite:2.5
      - andesite:2.5
      - gravel:2.5
      - coal_ore:3
      - DEEPSLATE_COAL_ORE:2.5
      - iron_ore:7
      - deepslate_iron_ore:8
      - gold_ore:12.5
      - deepslate_gold_ore:10.5
      - redstone_ore:3
      - DEEPSLATE:5.5
    5:
      - Stone:25
      - granite:2.5
      - diorite:2.5
      - andesite:2.5
      - gravel:2.5
      - DEEPSLATE_COAL_ORE:1
      - deepslate_iron_ore:13
      - gold_ore:3
      - deepslate_gold_ore:12.5
      - redstone_ore:5
      - deepslate_redstone_ore:15
      - DEEPSLATE:14
      - diamond_ore:1
      - deepslate_diamond_ore:0.5
    6:
      - deepslate:31.5
      - granite:2.5
      - diorite:2.5
      - andesite:2.5
      - gravel:2.5
      - DEEPSLATE_COAL_ORE:1
      - deepslate_iron_ore:10
      - deepslate_gold_ore:12.5
      - deepslate_redstone_ore:15
      - deepslate_diamond_ore:15
    7:
      - deepslate:30
      - granite:2.5
      - diorite:2.5
      - andesite:2.5
      - gravel:2.5
      - DEEPSLATE_COAL_ORE:1
      - deepslate_iron_ore:7.5
      - deepslate_gold_ore:10
      - deepslate_redstone_ore:12.5
      - deepslate_diamond_ore:12.5
      - deepslate_emerald_ore:11.5

  ForUpgrade: #Max 8 item & 7 level
    1:
      - Cobblestone:64
      - Iron_ingot:10
      - coal:10
      - granite:10
      - diorite:10
      - andesite:10
      - gravel:10
      - emerald:1