name: JustSkyblock
version: '${version}'
main: fr.ht06.justskyblock.JustSkyblock
api-version: '1.20'
author: ht06
depend:
  - WorldEdit
  - WorldBorderAPI
softdepend: [PlaceholderAPI]

commands:
  island:
    aliases:
      - is
    description: Create an island or teleport the player to his own island

  isadmin:
    description: Everything related to administration of the JustSkyblock
    permission: justskyblock.isadmin
    aliases:
      - islandadmin
      - isa

  #test:
    #description: fait chioer
    #permission: justskyblock.test



